version: "3"

services:
    db:
        container_name: cvt-oss-db-reports
        image: postgres
        volumes:
          - "psql-data-reports:/var/lib/postgresql/data"
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
    web:
        container_name: cvt-oss-web-reports
        build: .
        command: ./setup.sh
        volumes:
            - .:/opt/app-root/src
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - PDF_ANALYZER_URL

volumes:
    psql-data-reports:

networks:
    default:
        external:
            name: cvt-oss
