# Generated by Django 2.2.2 on 2019-06-13 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'active'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=40)),
                ('dt_payment', models.DateTimeField()),
                ('total', models.FloatField()),
            ],
            options={
                'ordering': ('transaction_id',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'active'),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('dt_start', models.DateField(blank=True, null=True)),
                ('dt_end', models.DateField(blank=True, null=True)),
                ('budget', models.PositiveIntegerField(default=0)),
                ('target_group', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Code')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Section')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('displays', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Campaign')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Invoice')),
            ],
            options={
                'ordering': ('invoice', 'campaign', 'name'),
            },
        ),
    ]
