# Generated by Django 2.2.2 on 2019-06-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190615_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='dt_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='reports.Invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('invoice', 'name')},
        ),
    ]
