# Generated by Django 2.2.2 on 2019-06-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190615_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Request'),
        ),
    ]
