# Generated by Django 2.2.2 on 2019-06-15 12:59

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20190615_1219'),
    ]

    operations = [
        TrigramExtension(),
    ]
