# Generated by Django 2.2.2 on 2019-06-16 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0007_auto_20190615_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('name',), 'verbose_name': 'Campaign in invoice', 'verbose_name_plural': 'Campaigns in invoice'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ('name', 'active'), 'verbose_name': 'Project code'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('name', 'active'), 'verbose_name': 'Project section'},
        ),
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='active',
            field=models.BooleanField(default=True, help_text='Show in dialogs'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dt_payment',
            field=models.DateTimeField(verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(max_length=40, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='approved',
            field=models.BooleanField(default=False, help_text='Approved by manager'),
        ),
        migrations.AlterField(
            model_name='request',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='Expected budget'),
        ),
        migrations.AlterField(
            model_name='request',
            name='code',
            field=models.ForeignKey(help_text='Project code', on_delete=django.db.models.deletion.CASCADE, to='reports.Code'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dt_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dt_end',
            field=models.DateField(blank=True, null=True, verbose_name='End of campaign'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dt_start',
            field=models.DateField(blank=True, null=True, verbose_name='Start of campaign'),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(help_text='Contat e-mail', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='request',
            name='link',
            field=models.URLField(blank=True, help_text='URL link to paid post', verbose_name='URL link'),
        ),
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.TextField(blank=True, help_text='Anything else'),
        ),
        migrations.AlterField(
            model_name='request',
            name='section',
            field=models.ForeignKey(help_text='Project section', on_delete=django.db.models.deletion.CASCADE, to='reports.Section'),
        ),
        migrations.AlterField(
            model_name='request',
            name='target_group',
            field=models.TextField(blank=True, help_text='Describe your target audience.'),
        ),
        migrations.AlterField(
            model_name='request',
            name='text',
            field=models.TextField(blank=True, help_text='Text of the post'),
        ),
        migrations.AlterField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True, help_text='Show in dialogs'),
        ),
    ]
