# Generated by Django 2.2.2 on 2019-06-16 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20190616_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dt_payment',
            field=models.DateTimeField(db_index=True, verbose_name='Payment date'),
        ),
    ]
