# Generated by Django 2.2.2 on 2019-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190616_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
