# Generated by Django 2.2.2 on 2019-06-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20190618_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_matched',
            field=models.BooleanField(default=False),
        ),
    ]
