# Generated by Django 2.2.2 on 2019-06-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_campaign_auto_matched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
    ]
