# Generated by Django 2.2.2 on 2019-06-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_remove_request_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together=set(),
        ),
    ]
